language: node_js
node_js:
  - '10.15.1'
dist: trusty
sudo: required
cache:
  directories:
    - node_modules
branches:
  only:
    - development
before_script:
  - npm i -g @angular/cli
script:
  - npm run lint
  - npm run build-prod
deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  skip_cleanup: true
  local_dir: dist
  on:
    repo: cade-tecnologia/cade-chat-frontend
    branch: development
after_deploy:
  - echo "URL -> cade-chat.web.app"
notifications:
  email: false
